### PR TITLE
Update extension.js

### PR DESCRIPTION
**Pull request by fiszermane**
Bug fix: heb strings appeared if portion was calculated on shabbat.

### CODE REVIEW

**Comment by amiad** [comment]
I not understanded what the bug. Are you can paste screenshot?

**Comment by fiszermane** [comment]
Sure. This is the bug:

untitled

When you use it in English, the name appears in Hebrew. The two lines I added force it to use English and fix it. It shouldn't affect if you use translation functionality.

**Comment by amiad** [comment]
You prefer the portion in English?

**Comment by fiszermane** [comment]
Actually, I don't mind. I thought that if the user sees everything in English why should he see that string in Hebrew, right? But if he wants the translated version in Hebrew, then he will get that string as well as everything else in Hebrew.

Anyway, your call, I'm totally fine with it.

**Comment by amiad** [comment]
I use Hebrew so you decide to English. Merged.

**Pull request merged**
